defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  
run:
  dir: logs/${model.params_model.name}_${datamodule.task}_s_${datamodule.sampling_rate[1]}

sweep:
  dir: logs/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}_${hydra.job.id}